### ISSUE TITLE
hacked main site?

### ISSUE THREAD

**Issue by SubZane** [sciactive/psteps#5]
The URL http://pinesframework.org/psteps/ leads to a spammy site and is linked to from http://sciactive.github.io/psteps/ :(

**Comment by amurrell** [comment]
I'm going to host it elsewhere then. Not sure what's up with it.

**Comment by Jayinthebay** [comment]
@amurrell it looks pretty good (and I've been looking at quite a few steps/wizard type of libraries) but it seems like you've lost the domain pinesframework.org to scamming scumbags. If you still have control of sciactive.github.io, you should remove that "caution warning danger..." block that directs people to the scammers all day long.

**Comment by hperrin** [comment]
Archiving repo.
